// GENERATED by tools/make_build_stamp.sh -- do not edit, do not commit edits.
// Shown on the self-test page as BUILD ddhh:mmss so a stale bitstream is
// obvious at a glance.
`define BUILD_STAMP 32'h22201126
